# Generated by Django 5.1 on 2025-05-17 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolios',
            fields=[
                ('port_id', models.IntegerField(primary_key=True, serialize=False)),
                ('port_img', models.ImageField(null=True, upload_to='')),
                ('port_link', models.CharField(max_length=50)),
                ('port_zip', models.FileField(null=True, upload_to='')),
            ],
        ),
    ]
