# Generated by Django 5.1 on 2025-05-17 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designesapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolios',
            name='port_link',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
