# Generated by Django 5.1 on 2025-05-17 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designesapp', '0002_alter_portfolios_port_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolios',
            name='port_img',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
