# Generated by Django 5.1 on 2025-05-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designesapp', '0003_alter_portfolios_port_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolios',
            name='port_zip',
            field=models.FileField(null=True, upload_to='file/'),
        ),
    ]
