# Generated by Django 5.1 on 2025-05-19 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designesapp', '0004_alter_portfolios_port_zip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('card_id', models.IntegerField(primary_key=True, serialize=False)),
                ('card_img', models.ImageField(null=True, upload_to='images/')),
                ('card_file', models.FileField(blank=True, null=True, upload_to='file/')),
            ],
        ),
    ]
