# Generated by Django 5.1 on 2025-05-19 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designesapp', '0005_cards'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resumes',
            fields=[
                ('resu_id', models.IntegerField(primary_key=True, serialize=False)),
                ('resu_img', models.ImageField(null=True, upload_to='images/')),
                ('resu_file', models.FileField(blank=True, null=True, upload_to='file/')),
            ],
        ),
        migrations.AlterField(
            model_name='portfolios',
            name='port_zip',
            field=models.FileField(blank=True, null=True, upload_to='file/'),
        ),
    ]
