# Generated by Django 5.1 on 2025-05-24 04:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designesapp', '0006_resumes_alter_portfolios_port_zip'),
    ]

    operations = [
        migrations.CreateModel(
            name='enquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80)),
                ('email', models.CharField(max_length=100)),
                ('contactno', models.CharField(max_length=15)),
                ('passw', models.CharField(max_length=50)),
                ('cpassw', models.CharField(max_length=50)),
                ('date', models.DateField(max_length=30)),
            ],
        ),
    ]
