# Generated by Django 5.1 on 2025-05-24 04:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designesapp', '0007_enquiry'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='enquiry',
            new_name='Createaccount',
        ),
    ]
