# Generated by Django 5.1 on 2025-05-24 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designesapp', '0008_rename_enquiry_createaccount'),
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.CharField(max_length=100)),
                ('passw', models.CharField(max_length=50)),
            ],
        ),
    ]
