# Generated by Django 5.1 on 2025-05-24 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designesapp', '0008_rename_enquiry_createaccount'),
    ]

    operations = [
        migrations.AddField(
            model_name='cards',
            name='card_link',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='resumes',
            name='resu_link',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
