# Generated by Django 5.1 on 2025-05-25 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designesapp', '0009_cards_card_link_resumes_resu_link'),
        ('designesapp', '0009_login'),
    ]

    operations = [
    ]
