# Generated by Django 5.1 on 2025-06-01 19:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designesapp', '0012_carddownloadrecord_portfoliodownloadrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliodownloadrecord',
            name='portfolio',
        ),
        migrations.AddField(
            model_name='downloadrecord',
            name='card',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='designesapp.cards'),
        ),
        migrations.AddField(
            model_name='downloadrecord',
            name='portfolio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='designesapp.portfolios'),
        ),
        migrations.AlterField(
            model_name='downloadrecord',
            name='resume',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='designesapp.resumes'),
        ),
        migrations.DeleteModel(
            name='CardDownloadRecord',
        ),
        migrations.DeleteModel(
            name='PortfolioDownloadRecord',
        ),
    ]
