# Generated by Django 5.1 on 2025-06-01 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('designesapp', '0015_carddownloadrecord'),
    ]

    operations = [
        migrations.CreateModel(
            name='Resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('profile_pic', models.ImageField(upload_to='profile_pics/')),
                ('about', models.TextField()),
                ('professional_skills', models.TextField()),
                ('personal_skills', models.TextField()),
                ('company_name', models.CharField(max_length=100)),
                ('company_details', models.TextField()),
                ('education_name', models.CharField(max_length=100)),
                ('education_details', models.TextField()),
            ],
        ),
        migrations.DeleteModel(
            name='CardDownloadRecord',
        ),
    ]
