# Generated by Django 5.1 on 2025-06-01 21:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designesapp', '0016_resume_delete_carddownloadrecord'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portfoliodownloadrecord',
            name='portfolio',
        ),
        migrations.DeleteModel(
            name='DownloadRecord',
        ),
        migrations.DeleteModel(
            name='PortfolioDownloadRecord',
        ),
    ]
