# Generated by Django 5.1 on 2025-06-01 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('designesapp', '0017_remove_portfoliodownloadrecord_portfolio_and_more'),
    ]

    operations = [
    ]
